apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-umami-consumer
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 30
  readiness:
    path: /internal/health
    initialDelay: 5
  replicas:
    min: 5
    max: 10
    scalingStrategy:
      kafka:
        topic: reops-insight-event
        consumerGroup: reops-umami-consumer
        threshold: 1000
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: "800m"
      memory: 256Mi
  kafka:
    pool: nav-prod
  accessPolicy:
    outbound:
      rules:
        - application: reops-umami-beta
      external:
        - host: nav-prod-kafka-nav-prod.aivencloud.com
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: kubernetes
    - name: REOPS_UMAMI_URL
      value: reops-umami-beta.team-researchops.svc.cluster.local
    - name: JAVA_TOOL_OPTIONS
      value: >-
        -XX:+UseZGC
        -XX:MaxRAMPercentage=70
        -XX:InitialRAMPercentage=50
        -XX:+ExitOnOutOfMemoryError
