apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-umami-consumer
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 30
  readiness:
    path: /internal/health
    initialDelay: 5
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: "50m"
      memory: 512Mi
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      rules:
        - application: umami
      external:
        - host: nav-dev-kafka-nav-dev.aivencloud.com
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: kubernetes
    - name: REOPS_UMAMI_URL
      value: "https://umami.ansatt.dev.nav.no"