apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-umami-consumer
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 30
  readiness:
    path: /internal/health
    initialDelay: 5
  replicas:
    min: 2
    max: 3
    scalingStrategy:
      cpu:
        thresholdPercentage: 70
      kafka:
        topic: team-researchops.analytics-raw
        consumerGroup: reops-umami-consumer-group
        threshold: 100
  observability:
    autoInstrumentation:
      enabled: true
      runtime: sdk
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: "200m"
      memory: 124Mi
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      rules:
        - application: umami
      external:
        - host: nav-dev-kafka-nav-dev.aivencloud.com
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: kubernetes
    - name: REOPS_UMAMI_URL
      value: "umami.team-researchops.svc.cluster.local"
    - name: JAVA_TOOL_OPTIONS
      value: >-
        -XX:+UseZGC
        -XX:MaxRAMPercentage=70
        -XX:InitialRAMPercentage=50
        -XX:+ExitOnOutOfMemoryError
  strategy:
    type: Recreate