spring:
  application:
    name: reops-umami-consumer
  kafka:
    bootstrap-servers: localhost:9094
    topic: test2
    dlq-topic: test2-dlq
    consumer:
      group-id: reops-umami-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        max.poll.records: 500
        max.poll.interval.ms: 300000
        fetch.max.bytes: 1048576  # 1 MB
        fetch.min.bytes: 1
        fetch.max.wait.ms: 100
  main:
    banner-mode: off
    web-application-type: reactive
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /internal/
      exposure:
        include: info, health, metrics, prometheus

reops:
  umami:
    url: http://localhost:3000
  dlq:
    retry-interval: PT10M

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    no.nav.reops: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: WARN
    reactor.netty.http.client: WARN
    org.apache.kafka.clients.NetworkClient: WARN
    org.apache.kafka.clients.Metadata: WARN
    org.apache.kafka.common.config.AbstractConfig: WARN
