spring:
  kafka:
    bootstrap-servers: localhost:9094
    topic: raw
    listener:
      concurrency: 1
    properties:
      security.protocol: PLAINTEXT
    retry:
      backoff-delay: 1000
server:
  port: 8084

reops:
  umami:
    url: http://localhost:3000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    no.nav.reops: TRACE
    org.springframework.kafka: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    reactor.netty.http.client: DEBUG
    org.apache.kafka.clients.NetworkClient: WARN
    org.apache.kafka.clients.Metadata: WARN