spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    topic: team-researchops.analytics-raw
    properties:
      security.protocol: SSL
      ssl.endpoint.identification.algorithm: ""
      ssl.truststore.type: JKS
      ssl.truststore.location: ${KAFKA_TRUSTSTORE_PATH}
      ssl.truststore.password: ${KAFKA_CREDSTORE_PASSWORD}
      ssl.keystore.type: PKCS12
      ssl.keystore.location: ${KAFKA_KEYSTORE_PATH}
      ssl.keystore.password: ${KAFKA_CREDSTORE_PASSWORD}
      ssl.key.password: ${KAFKA_CREDSTORE_PASSWORD}
      reconnect.backoff.ms: 5000
      reconnect.backoff.max.ms: 10000

reops:
  umami:
    url: ${REOPS_UMAMI_URL}

logging:
  structured:
    format:
      console: logstash

management:
  opentelemetry:
    tracing:
      export:
        otlp:
          transport: grpc
  otlp:
    metrics:
      export:
        enabled: false