apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    team: team-researchops
  name: total-kafka-umami-fails
  namespace: team-researchops
spec:
  groups:
    - name: reops-umami-consumer-alerts
      rules:
        - alert: EventErrorRateHigh
          expr: |
            sum(increase(kafka_events_dlt_total{namespace="team-researchops", app="reops-umami-consumer", result="failure"}[5m])) > 300
          for: 5m
          annotations:
            summary: "High error rate for reops-umami-consumer"
            consequence: "Consumer is unable to send events to umami."
            message: "reops-umami-consumer has {{ $value }} failed events over the last 5 minutes."
            dashboard_url: "https://grafana.nav.cloud.nais.io/d/reops-event-tracking/reops-event-tracking-proxy-2b-consumer"
          labels:
            severity: warning
            namespace: team-researchops