name: "Deploy"
run-name: "Deploy"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          dependency-graph: generate-and-submit
      - name: Build and test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build

  docker:
    name: "docker"
    runs-on: ubuntu-latest-8-cores
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker-build-push
        uses: nais/docker-build-push@v0
        with:
          team: team-researchops
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          build_args: CI=true
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-application-dev:
    needs: [test, docker]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Deploy application to Dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml
          VAR: image=${{ needs.docker.outputs.image }}

  deploy-application-prod:
    needs: [test, docker]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Deploy application to Prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais-prod.yaml
          VAR: image=${{ needs.docker.outputs.image }}
